
POST http://localhost:5130/FruitLuck
Content-Type: application/json 

{
    "name": "Vegan Fruitluck",
    "description": "I When I move out, I will get a new desk once I save up enough money, I want it to be a convertible standing desk and I.",
    "startDateTime": "2023-12-29T07:00:00",
    "endDateTime": "2023-12-30T11:00:00",  
    "Fruits": [
        "Atemoya",
        "Cherimoya",
        "Mango",
        "Sugar Apple",
        "Gynura Procumbens"
    ] 
}

###



GET https://localhost:5130/fruitLucks/e35daaba-5a9e-43a2-9305-3dead8296fe0